// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScoringServiceAPI.Data;

#nullable disable

namespace ScoringServiceAPI.Migrations
{
    [DbContext(typeof(ScoringDbContext))]
    partial class ScoringDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScoringServiceAPI.Models.ClientScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ClientScores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = "C001",
                            Score = 750,
                            UpdatedAt = new DateTime(2025, 10, 8, 8, 32, 34, 442, DateTimeKind.Utc).AddTicks(7534)
                        },
                        new
                        {
                            Id = 2,
                            ClientId = "C002",
                            Score = 620,
                            UpdatedAt = new DateTime(2025, 10, 8, 8, 32, 34, 442, DateTimeKind.Utc).AddTicks(7732)
                        },
                        new
                        {
                            Id = 3,
                            ClientId = "C003",
                            Score = 450,
                            UpdatedAt = new DateTime(2025, 10, 8, 8, 32, 34, 442, DateTimeKind.Utc).AddTicks(7733)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
